/**
 * SHARED CONTRACTS — FROZEN AFTER FAN-OUT (integrator-owned).
 *
 * Every agent imports from '@/types/contracts' and codes against these fixed
 * shapes. Do NOT edit this file once agents have fanned out — it is the
 * compiler-enforced boundary that keeps parallel work decoupled.
 *
 * Replace the examples below with your app's real contracts BEFORE fan-out.
 * Keep one example of each kind (model, store, service, component props).
 */

// --- Domain models ---
export type ID = string;

export interface MoodEntry {
  id: ID;
  score: 1 | 2 | 3 | 4 | 5;
  note?: string;
  createdAt: number; // epoch ms
}

// --- Store contract: what a zustand slice exposes to the UI ---
export interface MoodStore {
  entries: MoodEntry[];
  add: (score: MoodEntry['score'], note?: string) => void;
  clear: () => void;
}

// --- Service / API signature ---
export type FetchEntries = () => Promise<MoodEntry[]>;

// --- Component prop interface: a shared feature component's props ---
export interface EntryCardProps {
  entry: MoodEntry;
  onPress?: (id: ID) => void;
}

// --- Writing kit ---
export interface WritingEntry {
  id: ID;
  title: string;
  body: string;
  imageUri?: string;
  createdAt: number; // epoch ms
  updatedAt: number; // epoch ms
}

export interface WritingDraft {
  id?: ID; // present → update that entry; absent → create
  title: string;
  body: string;
  imageUri?: string;
}

export interface WritingStore {
  entries: WritingEntry[];
  upsert: (draft: WritingDraft) => ID;
  removeMany: (ids: ID[]) => void;
  clear: () => void;
}
