/**
 * SHARED CONTRACTS — FROZEN AT FAN-OUT (integrator-owned).
 *
 * Every agent imports from '@/types/contracts' and codes against these fixed
 * shapes. Do NOT edit this file — it is the compiler-enforced boundary that keeps
 * parallel work decoupled.
 *
 * THE PRODUCT IN ONE PARAGRAPH: the writer speaks an instruction; the LLM returns
 * the FULL revised markdown; we diff it against what they had; they accept or
 * reject each change. Nothing the AI writes reaches the manuscript unreviewed.
 */

export type ID = string;

// ---------------------------------------------------------------------------
// The document
// ---------------------------------------------------------------------------

/**
 * Markdown is the single source of truth. Not HTML: the diff has to be legible
 * to a human deciding what happens to their prose, and an HTML diff is dominated
 * by tag and attribute noise. The rich-text editor is a *view* over this string.
 */
export interface DocumentSnapshot {
  id: ID;
  markdown: string;
  /** Server-assigned, monotonic. Bumped on every accepted write. */
  version: number;
  updatedAt: number; // epoch ms
}

/** One entry in the server-side version stack — makes undo/history cheap. */
export interface DocumentVersion {
  version: number;
  markdown: string;
  createdAt: number; // epoch ms
  /** Why this version exists, e.g. the instruction that produced it. */
  label?: string;
}

/** Single-document POC: there is exactly one, and this is its id. */
export const DOCUMENT_ID: ID = 'default';

// ---------------------------------------------------------------------------
// The diff
// ---------------------------------------------------------------------------

export type HunkKind = 'insert' | 'delete' | 'replace';

/**
 * One reviewable change. Offsets index into the BASE markdown the diff was
 * computed against, and hunks never overlap — together those two facts are what
 * make "accept this one, reject that one" a pure function (see applyDecisions).
 */
export interface Hunk {
  id: ID;
  kind: HunkKind;
  /** Inclusive start offset into base markdown. */
  start: number;
  /** Exclusive end offset. start === end for a pure insertion. */
  end: number;
  /** Exactly base.slice(start, end). Empty for a pure insertion. */
  before: string;
  /** Replacement text. Empty for a pure deletion. */
  after: string;
}

/**
 * Kept OUT of Hunk on purpose. A hunk is what the AI proposed; a decision is what
 * the writer said about it. One field must not answer two questions — merging
 * them is how you end up with a state you can't get out of.
 */
export type HunkDecision = 'pending' | 'accepted' | 'rejected';

/** Renderer input: the base text sliced into untouched runs and reviewable hunks. */
export type DiffSegment =
  | { kind: 'equal'; text: string }
  | { kind: 'hunk'; hunk: Hunk };

/** A round trip the writer is currently reviewing. */
export interface EditProposal {
  id: ID;
  /** The transcribed voice instruction that produced it — shown verbatim. */
  instruction: string;
  /** The markdown the diff was computed against. Decisions are meaningless without it. */
  baseMarkdown: string;
  /** The model's full revised document, before any accept/reject filtering. */
  revisedMarkdown: string;
  hunks: Hunk[];
  createdAt: number;
}

// --- Diff engine signatures (Agent A) --------------------------------------

/** Pure. Same inputs → same hunks, including ids. */
export type ComputeHunks = (base: string, revised: string) => Hunk[];

/** Pure. Slices `base` into equal runs and hunks, in document order. */
export type LayoutDiff = (base: string, hunks: Hunk[]) => DiffSegment[];

/**
 * Pure. The heart of the product: rebuild the document with only the accepted
 * hunks applied. `pending` counts as NOT applied — the writer has to say yes.
 */
export type ApplyDecisions = (
  base: string,
  hunks: Hunk[],
  decisions: Readonly<Record<ID, HunkDecision>>
) => string;

// ---------------------------------------------------------------------------
// Server API (Agent B implements the handlers; the client lives in @/lib/api)
// ---------------------------------------------------------------------------

/** GET /api/document → DocumentSnapshot */
export type GetDocumentResponse = DocumentSnapshot;

/** PUT /api/document */
export interface PutDocumentRequest {
  markdown: string;
  /** The version the client believed it was editing. Last-write-wins; this is telemetry. */
  baseVersion?: number;
  /** Recorded on the version stack entry. */
  label?: string;
}
export type PutDocumentResponse = DocumentSnapshot;

/** GET /api/versions → newest first, capped server-side. */
export interface GetVersionsResponse {
  versions: DocumentVersion[];
}

/** POST /api/edit — send the whole document, get the whole document back. */
export interface EditRequest {
  markdown: string;
  instruction: string;
  /** Proper nouns to preserve verbatim. Extra credit; safe to omit. */
  dictionary?: string[];
}
export interface EditResponse {
  revisedMarkdown: string;
}

/** Every endpoint returns this shape on failure. */
export interface ApiError {
  error: string;
}

// ---------------------------------------------------------------------------
// Client-side stores
// ---------------------------------------------------------------------------

/**
 * Sync is a visible state, in words, never a silent spinner — the writer needs to
 * know their manuscript is safe.
 */
export type SyncStatus = 'idle' | 'loading' | 'saving' | 'error';

export const SYNC_STATUS_LABEL: Record<SyncStatus, string> = {
  idle: 'Saved',
  loading: 'Opening…',
  saving: 'Saving…',
  error: 'Not saved',
};

/** Agent C owns the implementation in src/store/doc.ts. */
export interface DocStore {
  markdown: string;
  version: number;
  status: SyncStatus;
  /** Human-readable; null unless status === 'error'. */
  error: string | null;
  lastSyncedAt: number | null;
  /** Cold start: GET the document, falling back to the seeded sample. */
  load: () => Promise<void>;
  /** A local edit (human typing OR accepted hunks). Schedules a debounced save. */
  setMarkdown: (markdown: string, label?: string) => void;
  /** Flush any pending save immediately. */
  flush: () => Promise<void>;
}

// ---------------------------------------------------------------------------
// Component props
// ---------------------------------------------------------------------------

/** Agent C owns the implementation in src/components/editor/. */
export interface MarkdownEditorProps {
  markdown: string;
  onChangeMarkdown: (markdown: string) => void;
  editable?: boolean;
  /** Called once the webview has loaded and round-tripped its first value. */
  onReady?: () => void;
}
